### ISSUE TITLE
New Release 21.1.4 ?

### ISSUE THREAD

**Issue by danielhoherd** [aantn/pytest-kind#1]
There were several commits after 21.1.3. See <https://github.com/aantn/pytest-kind/compare/5d3a55d7c1ce011ffb9a7fc9f945b9630f374f34..main>. Can we get a new release for this version? Or better yet, re-lock poetry and then release a new version? There are some great features that are missing from the latest pypi release.

**Comment by aantn** [comment]
Hi @danielhoherd, this is a fork of https://codeberg.org/hjacobs/pytest-kind 

I don't have permission to push a release to PyPi - perhaps contact hjacobs about it.

I'd love for my changes to be merged into the main repo. I originally made the changes to support using pytest-kind at @robusta-dev but we had to abandon pytest-kind because the GPL license was problematic. (We're MIT licensed ourself.)

**Comment by aantn** [comment]
If you're curious, you can see how we currently setup kind clusters using GitHub actions [here](https://github.com/robusta-dev/robusta/blob/master/.github/workflows/test_robusta.yaml#L15)

**Comment by danielhoherd** [comment]
Oh, interesting. Looks like somebody did some similar changes to that repo https://codeberg.org/hjacobs/pytest-kind/pulls/9/files and it looks like those are included in the current release.

Thanks for info on how you set up your kind cluster. We've already got [shell based kind setup](https://github.com/astronomer/astronomer/blob/master/bin/setup-kind) but were looking at something more tightly integrated with pytest.

It's always frustrating when licensing gets in the way of collaborative engineering. 😕 I completely understand though. Love that MIT license.

**Comment by danielhoherd** [comment]
FWIW I opened the same issue upstream https://codeberg.org/hjacobs/pytest-kind/issues/20

**Comment by aantn** [comment]
Yep. I like your Tech Notes btw and Astronomer looks cool.
